# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: uav/pose
        pose2d: uav/ground_pose
        child_frame_id: body
        parent_frame_id: world

